name: trackmate_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
#  firebase_core: ^3.15.2
#  firebase_auth: ^5.7.0

  # OTP & UI
  email_otp_auth: ^1.1.0
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8

  # Location & Permissions
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1

  # State Management
  provider: ^6.1.1

  # Storage
  shared_preferences: ^2.2.2

  # Utilities
  uuid: ^4.2.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
