name: trackmate_app
description: "Smart travel assistant with authentication, maps, analytics, booking & AI tools."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # -------- State Management & Storage --------
  get: ^4.6.6
  get_storage: ^2.1.1
  shared_preferences: ^2.3.2

  # -------- Localization --------
  flutter_localizations:
    sdk: flutter

  # -------- Networking --------
  http: ^1.2.2

  # -------- Charts & UI --------
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  animations: ^2.0.11
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0

  # -------- Backend & Auth --------
  email_otp_auth: ^1.1.0
  flutter_dotenv: ^5.1.0

  # -------- Maps + GPS --------
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.9.0
  location: ^5.0.3

  # -------- Contacts --------
  flutter_contacts: ^1.1.9+2

  # -------- Utility --------
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

# ðŸš€ APP ICON CONFIG
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/Rectangle.png
    - assets/ill 3.png
    - .env